version: "3.9"
services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    networks:
      - analysisnetwork

  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analysisdb
    ports:
      - 5432:5432
    volumes:
      - analysisdb:/var/lib/postgresql/data

    networks:
      - analysisnetwork

volumes:
  analysisdb:

networks:
  analysisnetwork:
