version: "3.9"
services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    networks:
      - gamesnetwork

  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamesdb
    ports:
      - 5432:5432
    volumes:
      - gamesdb:/var/lib/postgresql/data

    networks:
      - gamesnetwork

volumes:
  gamesdb:

networks:
  gamesnetwork:
